name: 'Dev: CS API FO - CI/CD - Auto'

on:
  push:
    tags:
      - 'dev-api-[0-9]*.[0-9]*.[0-9]*' # Matches tags like dev-api-0.36.0

jobs:
  call-ci-cd-workflow:
    uses: ./.github/workflows/s3-ci-cd-template.yml
    with:
      AWS_ACCOUNT_ID: '062029356220'
      DEPLOYMENT_ENV: development
      TARGET_APP: api-console
      S3_BUCKET_DIR: dev-saforus-asset/webapp/fo/
      CLOUDFRONT_DISTRIBUTION_ID: E20FL0JHYOF2N9
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
