name: 'Dev: CS API DOC - CI/CD - Auto'

on:
  push:
    tags:
      - 'dev-api-doc-[0-9]*.[0-9]*.[0-9]*' # Matches tags like dev-api-doc-0.36.0

jobs:
  call-ci-cd-workflow:
    uses: ./.github/workflows/s3-ci-cd-template.yml
    with:
      AWS_ACCOUNT_ID: '062029356220'
      DEPLOYMENT_ENV: development
      TARGET_APP: api-docs
      S3_BUCKET_DIR: dev-saforus-asset/webapp/docs/
      CLOUDFRONT_DISTRIBUTION_ID: E1Y7CS7QY6VVFN
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
