name: 'Prod: Saforus BO - CI/CD - Auto'

on:
  push:
    tags:
      - 'prod-[0-9]*.[0-9]*.[0-9]*' # Matches tags like prod-0.36.0
      - 'prod-bo-[0-9]*.[0-9]*.[0-9]*' # Matches tags like prod-bo-0.36.0

jobs:
  call-ci-cd-workflow:
    uses: ./.github/workflows/ci-cd-template.yml
    with:
      AWS_ACCOUNT_ID: '805405624138'
      ECS_CLUSTER: prod-cs-cluster
      DEPLOYMENT_ENV: production
      TARGET_APP: saforus-bo
      CPU_SIZE: 256
      MEMORY_SIZE: 512
      SVC_PORT: 80
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
