name: 'Prod: CS API FO - CI/CD - Auto'

on:
  push:
    tags:
      - 'prod-api-[0-9]*.[0-9]*.[0-9]*' # Matches tags like prod-api-0.36.0

jobs:
  call-ci-cd-workflow:
    uses: ./.github/workflows/s3-ci-cd-template.yml
    with:
      AWS_ACCOUNT_ID: '805405624138'
      DEPLOYMENT_ENV: production
      TARGET_APP: api-console
      S3_BUCKET_DIR: saforus-asset/webapp/fo/
      CLOUDFRONT_DISTRIBUTION_ID: EYPMW8HZ7233L
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
