name: 'Prod: CS API BO - CI/CD - Auto'

on:
  push:
    tags:
      - 'prod-api-bo-[0-9]*.[0-9]*.[0-9]*' # Matches tags like prod-api-bo-0.36.0

jobs:
  call-ci-cd-workflow:
    uses: ./.github/workflows/s3-ci-cd-template.yml
    with:
      AWS_ACCOUNT_ID: '805405624138'
      DEPLOYMENT_ENV: production
      TARGET_APP: api-bo
      S3_BUCKET_DIR: saforus-asset/webapp/bo/
      CLOUDFRONT_DISTRIBUTION_ID: E22YGM7ZSBE26R
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
