name: 'Stag: CS API DOC - CI/CD - Auto'

on:
  push:
    tags:
      - 'stage-api-doc-[0-9]*.[0-9]*.[0-9]*' # Matches tags like stage-api-doc-0.36.0

jobs:
  call-ci-cd-workflow:
    uses: ./.github/workflows/s3-ci-cd-template.yml
    with:
      AWS_ACCOUNT_ID: '062029356220'
      DEPLOYMENT_ENV: staging
      TARGET_APP: api-docs
      S3_BUCKET_DIR: stag-saforus-asset/webapp/docs/
      CLOUDFRONT_DISTRIBUTION_ID: E2QN0KXN7MG8ZS
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
